library(httr)
library(XML)
library(dplyr)
library(magrittr)
library(xml2)
library(rvest)
library(iotools)
library(DT)
library(jsonlite)
library(shiny)
library(shinythemes)
library(qrcode)

wsop_url <- "https://www.wsop.com/players/profile/?playerid="
ids <- c(315691,271,267,273)
names <- c("Ben Steinwachs","Phil Hellmuth","Dnegs","Phil Ivey")